# Generated by Django 3.0.7 on 2020-06-25 12:27

import ckeditor.fields
import django.core.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200619_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=ckeditor.fields.RichTextField(null=True, validators=[django.core.validators.MinLengthValidator(200)]),
        ),
    ]
